### ISSUE TITLE
Alternative to named functions

### ISSUE THREAD

**Issue by cpsubrian** [carlos8f/codemap#2]
The named functions have grown on me and I don't mind them being the recommended/primary way of specifying containers (especially in the node environment). However for browser/react-native environments where we want to or have to deal with minified code, there needs to be an alternative.

The easiest solution would be export a helper function that sets a property on a wrapped function that codemap looks at in addition to the 'name'. Something like:

``` js
// Codemap provides:
export.container = function (fn) {
  return Object.defineProperty(function () {
    return fn.apply(this, arguments)
  }, '_name', {value: 'container'})
}

// Usage (in an ES6 module):
import {container} from 'codemap'
export default {
  _ns: 'myNamespace',
  foo: container((get, set) => {
    return get('bar')
  })
}
```

**Comment by cpsubrian** [comment]
Note: I'm currently doing exactly this in a local fork.

**Comment by cpsubrian** [comment]
Perhaps instead of `_name` you could use something more semantic like `_isContainer`.

**Comment by carlos8f** [comment]
i like this approach, will accept a pr 👍

**Comment by cpsubrian** [comment]
@carlos8f K will sneak it in sometime
